### ISSUE TITLE
Dark mode "system" does not work

### ISSUE THREAD

**Issue by WhyNotHugo** [Nheko-Reborn/nheko#1067]
### Describe the bug

Picking theme "system" does not switch light / dark mode according to the system setting. It's just light all the time.

### To Reproduce

1. In Settings > General, under "Theme" pick "System".

### What happened?

Just a light theme (the system is currently in dark mode due to it being night time)

### Expected behavior

Should be dark mode right now.

### Screenshots

![image](https://user-images.githubusercontent.com/730811/165830544-c2464cf4-2d38-4dd2-b0ae-73c0423627bb.png)

### Version

0.9.3-9bac429

### Operating system

Linux

### Installation method

Flathub

### Qt version

(included in flatpak)

### Desktop Environment

swaywm (wayland)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
Nothing present.
```

**Comment by WhyNotHugo** [comment]
Being a cross-platform app, maybe additional notes are useful:

There's currently a relatively new spec to determine whether the system should currently be in light mode or dark mode. It's queried via D-Bus using the [org.freedesktop.portal.Settings](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings) interface.

It's supported on Gnome, ElementaryOS and KDE. I myself have authored and maintain `darkman`, a little daemon that switches dark mode / light mode for non-DE users. It implements this same spec.

**Comment by WhyNotHugo** [comment]
I tried monitoring D-Bus when nheko runs, and its seems it's not querying the current mode at all -- so maybe this feature is not implemented for Linux?

**Comment by LorenDB** [comment]
The system theme option means that nheko will try to use whatever Qt theme you have set on your computer instead of using one of its bundled themes. To override the Qt theme, you'll want to set QT_QPA_PLATFORMTHEME to a Qt theme (e.g. breeze, kvantum, or qt5ct).

**Comment by LorenDB** [comment]
The D-Bus parameter sounds interesting, though. I might look into using it for first run theme configuration.

**Comment by WhyNotHugo** [comment]
Oh, right. Given that the only other two choices are "dark" and "light", I though that theme simply toggled dark mode. My bad.

> To override the Qt theme, you'll want to set QT_QPA_PLATFORMTHEME to a Qt theme (e.g. breeze, kvantum, or qt5ct).

I guess I could have a wrapper script that sets that based on the current mode -- but given that it's an environment variable, I can't later [programatically] change the theme at runtime.

Sounds like what I'm asking for is really a new feature, not a bug (sorry, misinterpreted what that setting does). Support for the D-Bus setting would be super :+1:

**Comment by deepbluev7** [comment]
Qt6 also has an Application property if thr system is using a dark or light mode

**Comment by WhyNotHugo** [comment]
> Qt6 also has an Application property if thr system is using a dark or light mode

This sounds very reasonable. I expect Qt to use the above mentioned API... if it doesn't, then it's something I'd rather report to Qt itself.

**Comment by LorenDB** [comment]
I don't think it's necessarily a Qt issue. I'd suggest trying to make a script setup that changes the Qt theme in qt5ct, and then set your system Qt theme to qt5ct.

**Comment by WhyNotHugo** [comment]
qt5ct breaks other applications (and their icons). I prefer to stick as close as possible to the defaults.

It seems that what I'm trying to change is known in Qt as "colour scheme", not "theme". I guess this also can't be changed at runtime?

> The D-Bus parameter sounds interesting, though. I might look into using it for first run theme configuration.

There's also an associated signal to receive notifications each time it changes.

**Comment by deepbluev7** [comment]
It should just work correctly once we switch to Qt6 :)

**Comment by deepbluev7** [comment]
Should be fixed now :)

**Comment by balejk** [comment]
@deepbluev7 With nheko 0.12.0, the colorscheme autodetection still doesn't seem to work for me, at least if I understand correctly how it should work.

I'm on Void Linux with Qt 6.6 and I have set up the xdg-desktop-portal and darkman according to [this](https://whynothugo.nl/journal/2024/04/09/darkman-portal-configuration/) on sway. Firefox changes the preferred colorscheme correctly when I switch it via darkman but nheko with `Theme: System` stays light. I tried restarting nheko too. `gdbus` queries suggested by @WhyNotHugo reveal that everything should be fine on darkman's side -- the corresponding property does change when the darkman setting is switched.

**Comment by WhyNotHugo** [comment]
The `gdbus` command used to confirm that the xdg-desktop-portal is properly relaying the value from `darkman` is:

    gdbus call --session --dest org.freedesktop.portal.Desktop --object-path /org/freedesktop/portal/desktop --method org.freedesktop.portal.Settings.Read org.freedesktop.appearance color-scheme

**Comment by DashieTM** [comment]
This seems to be a regression as it worked before 0.12.0. The theme is picked up but not applied properly for me, e.g. using the system theme results in a slightly darker light theme.

**Comment by balejk** [comment]
> This seems to be a regression as it worked before 0.12.0.

I see, that's interesting. I tried running a nightly version of nheko at
some point last year mainly to have this working but it did not work for
me then either, although in the hindsight I'm not entirely sure whether
I had the XDG portal set up correctly at that time.

> The theme is picked up but not applied properly for me, e.g. using the system theme results in a slightly darker light theme.

I'm not sure what you mean by "picked up" but system results in a
slightly darker light for me too, with or without the portal -- I assume
this is some kind of a Qt default.

@WhyNotHugo I see that Alpine has updated nheko too, have you been able
to verify that this is really still an issue yet? If so, perhaps you
could reopen this?
