### ISSUE TITLE
SSO works only once

### ISSUE THREAD

**Issue by AlexCzar** [Nheko-Reborn/nheko#249]
### Describe the bug
SSO login works only once, after I've restarted my PC and login was lost when I try to relogin, whole SSO process works to a point, I get "SSO success" message on the localhost redirect page, but then nheko says, that key setup fails, here's screenshot:
![image](https://user-images.githubusercontent.com/1010298/88152651-6212cc00-cc15-11ea-8088-1c5e07b352b6.png)

- Nheko version: 0.7.2
- Installation method: Flathub
- Operating System: Opensuse Tumbleweed latest
- Desktop Environment: KDE Plasma

### Logs

```text
[crypto] [critical] failed to upload one time keys: One time key <!-- snip --> already exists. Old key: {"key":"<!-- snip -->","signatures":{"@alex.czar:mozilla.org":{"<!-- snip -->":"<!-- snip -->"}}}; new key: {'key': '<!-- snip -->', 'signatures': {'@alex.czar:mozilla.org': {'<!-- snip -->': '<!-- snip -->'}}} 400

[ui] [info] dropping to the login page: Failed to setup encryption keys. Server response: One time key <!-- snip --> already exists. Old key: {"key":"<!-- snip -->","signatures":{"@alex.czar:mozilla.org":{"<!-- snip -->":"<!-- snip -->"}}}; new key: {'key': '<!-- snip -->', 'signatures': {'@alex.czar:mozilla.org': {'<!-- snip -->': '<!-- snip -->'}}} 400. Please try again later.
```

**Comment by deepbluev7** [comment]
Did your cache directory with your encryption keys get deleted in the mean time? This looks like the config file was kept around but the database got deleted (independently of SSO).

**Comment by AlexCzar** [comment]
if it was it was not done by me.
I see there is this directory present: `/home/me/.var/app/io.github.NhekoReborn.Nheko/cache/nheko/nheko`

**Comment by deepbluev7** [comment]
I can't really reproduce this on my end. For me SSO works, even if I restart Nheko. Could you retry and see, if the issue is reproduceable? Maybe delete your cache and config files before retrying? Is your ~/.var a tmpfs?

**Comment by qazip** [comment]
This is happening to me on "Login". I don't use "SSO Login". I login, close nheko. Open nheko and see that message. Every single time.

I am on Arch, using nheko 0.8.1-98b2df43.

**Comment by qazip** [comment]
Found the culprit. If I disable firejail for nheko, it functions properly.

**Comment by deepbluev7** [comment]
My guess is that because we need to listen on a port to get the response from the browser, firejail blocks that?

**Comment by deepbluev7** [comment]
To me it sounds like private-cache would cause issues, but we recently moved that to a different directory (the data dir), so it should work now?

**Comment by qazip** [comment]
I just re-compiled nheko and I am still having the same issue with firejail. I removed private-cache from firejail's profile and still having the same issue, so it is not that.

**Comment by qazip** [comment]
I just tested commenting lines in the firejail profile, rhoughly 3 by 3, and running nheko. Nothing fixed the issue, which points to there being a directory that should be whitelisted but is not?

**Comment by qazip** [comment]
While running with firejail, nheko doesn't write anything to ~/.cache/nheko/nheko. Without firejail, it writes to that folder. So that is the issue somewhy.

**Comment by deepbluev7** [comment]
Does firejail set the XDG directories to different values maybe, so Nheko tries to write to them instead?

**Comment by qazip** [comment]
This was solved in firejail: https://github.com/netblue30/firejail/issues/4115

**Comment by AlexCzar** [comment]
I do not use firejail, this is the first time I'm even hearing about it.

**Comment by deepbluev7** [comment]
Do you have ~/.cache or ~/.local/share mounted as a tmpfs?

**Comment by AlexCzar** [comment]
No.

**Comment by deepbluev7** [comment]
Fixed, was a flatpak issue. Requires flatpak 1.11.1 and the latest nightly (at the moment).
