### ISSUE TITLE
"No Room Open" and nothing given to resolve it

### ISSUE THREAD

**Issue by thewoose** [Nheko-Reborn/nheko#730]
### Describe the bug

I opened up Nheko today to see a screen that said nothing but "No Room Open."  I could not push any button, esacpe in any way, or do anything.  Uninstalling on MacOS Catalina didn't help because the personal files are hidden somewhere apparently.  Last time it was open there were numerous rooms filling the screen.  

### To Reproduce

Open nheko when you're unlucky.

Watch it say "No Room Open" and laugh at you.

### What happened?

I can't do anything!

### Expected behavior

To use Matrix of course!

### Version

I can't tell because it's hidden like everything else.

### Operating system

macOS

### Installation method

macOS DMG file

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
No Room Open.  No Reason Given.  Forget you user.
```

### Backtrace

```shell
Silly.
```

**Comment by iambumblehead** [comment]
I notice this issue using the nightly release on MacOS.

<img width="888" alt="Screen Shot 2021-10-01 at 1 02 53 PM" src="https://user-images.githubusercontent.com/2058705/135679828-0a3ecc3f-384a-40f8-a29b-db6f0b06ce6a.png">
 
I'm able to, sometimes, trigger this behaviour by resizing the window and then clicking twice (not rapidly) on a different room in the rooms list. It is harder to reproduce when the window is smaller and sometimes I need to resize the window several times. I've seen the issue when the window is 'big' and when the window is 'small'.

**Comment by deepbluev7** [comment]
There should now be a back button, if that issue appears, I hope. I still have a hard time reproducing this!

**Comment by deepbluev7** [comment]
Ah, wait, maybe I am misunderstanding this. You can close a room by double clicking it. That is intentional (i.e. when you don't want to accidentally mark any room as read). @LorenDB added that in https://github.com/Nheko-Reborn/nheko/pull/678 so he can defend that behaviour.

**Comment by LorenDB** [comment]
DON'T ANYBODY TOUCH MY CODE!!!

Seriously, I demand that the close room feature be included in some way, shape, or form, and I think that clicking a room again to deselect makes sense.

**Comment by LorenDB** [comment]
> using the latest nightly on mac os big sur,
>  * click room name; keep the mouse over the room name; click room name again
>     * result: no change happens
>  * click room name; mouse out from room name; mouse over room name; click room name
>     * result: room name is deselected and "no room open" is shown

This is actually a known bug; you have to move the mouse to get the deselect to work.

**Comment by deepbluev7** [comment]
> This is actually a known bug; you have to move the mouse to get the deselect to work.

I fixed that almost an hour ago!

**Comment by LorenDB** [comment]
Oh nice!

**Comment by LorenDB** [comment]
@thewoose I haven't had any trouble with this personally; are there any outstanding bugs remaining with this that needed addressed or is this issue more along the lines of "I was surprised by unexpected new functionality?"

**Comment by deepbluev7** [comment]
This doesn't seem to be actionable.
