### ISSUE TITLE
Timestamps in sidebar cut off and not aligned correctly

### ISSUE THREAD

**Issue by fnetX** [Nheko-Reborn/nheko#820]
### Describe the bug

Timestamps from recent chats in the timeline are cut off and generally not aligned correctly. Note that they behave differently.

### To Reproduce

1. Have nheko open for a while
2. spot timestamps being cut off
3. resize sidebar and see how they behave

Font settings:
- Font size: 10.5 (increased from 10 to 11 and back to 10.5 today)
- Font Famil (cut off, maybe related): nothing selected (didn't touch it recently)
- Emoji Font Famil: Noto Color Emoji
- theme: Dark
- System settings: Set scale factor to 1.1 today, didn't seem to affect nheko (will check)

### What happened?

see bug description.

### Expected behavior

They should always stay fully visible and aligned to the sidebar.

### Screenshots

Video:
https://user-images.githubusercontent.com/19634137/142705034-980000e7-cec6-40b2-b311-c962c241e11c.mp4

### Version

0.9.0-f32acdd | Linux

### Operating system

Linux

### Installation method

Flathub

### Desktop Environment

Cinnamon (on LMDE so pretty recent)

### Did you use profiles?

- [ ] Profiles used?

### Relevant log output

```shell
nothing obvious
```

**Comment by fnetX** [comment]
- still broken after resetting my font scaling to 1.0 in the system settings
- still broken after resetting font scale in nheko to 10pt
- still broken after setting font in nheko to "Noto Sans", "Open Sans" or "Roboto" (to try something more uncommon)

But the cut of text in the nheko setings is gone now. This is an effect of system scale. Will file a separate issue.

**Comment by fnetX** [comment]
I think this is related to how the text is shortened in the preview. It looks like each time a new letter is shown / hidden, the timestamp jumps for the amount of the new letter. It "works" for those chats that don't have long text in the recent message.

Is the timestamp aligned to a box which is aligned to the length of the rendered text or something?

**Comment by fnetX** [comment]
I don't know if my eyes are great, but it appears to me that the font size is larger for those chats that break, and the smaller ones work.

Have a look at this screenshot (it's actually difficult because I wanted to hide the name, but I added a straight red line and you can spot there is a small difference in the space between the colon and the line for the very same user name (so apparently the font size is slightly different, and that's what I also noticed when looking at it).
![Screenshot from 2021-11-20 01-29-28](https://user-images.githubusercontent.com/19634137/142707350-82b8e27c-7f7b-4d4d-b375-ca2c8011eedb.png)

**Comment by maltee1** [comment]
This appears to happen whenever the last message contains emoji (or possibly some kind of formatting) and cannot be displayed fully in the given space. My guess is that either Qt or Nheko doesn't correctly calculate the elideWidth of the label in that case. The Layout is then pushed off the edge of the room list and takes the timestamp with it. Improving the layouting code should at least put the timestamp where it belongs.
I'll give this one a shot.

**Comment by maltee1** [comment]
Fixed by https://github.com/Nheko-Reborn/nheko/pull/966

**Comment by fnetX** [comment]
Thank you very much. Should I close or do you want to keep this open so you (or someone else) can still have a look at the correct width calculation?
